### ISSUE TITLE
AWS::EC2::FlowLog shows error when adding the Tags item

### ISSUE THREAD

**Issue by Papina** [aws-cloudformation/aws-cfn-lint-visual-studio-code#127]
adding this code shows the Tags Property as error:

CloudFormation deploys the template fine with the expected tags

```
[cfn-lint] E3002: Invalid Property Resources/FlowLog/Properties/Tags
Peek Problem (⌥F8)
No quick fixes available

```

```
  #--------------------------------------------------------------------------------------------------
  FlowLog:
  #--------------------------------------------------------------------------------------------------
    Type: AWS::EC2::FlowLog
    Condition: EnableFlowLogs
    Properties:
      LogDestination: !Sub "arn:aws:s3:::${FlowLogsS3Bucket}/"
      LogDestinationType: !Ref FlowLogsLogDestinationType
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
      Tags:
        - Key: Name
          Value: test
```
