### ISSUE TITLE
False alert in AWS::EC2::LaunchTemplate

### ISSUE THREAD

**Issue by ccruzado** [aws-cloudformation/aws-cfn-lint-visual-studio-code#162]
When I created a LaunchTemplate I saw and error in TagSpecifications with the Cloudformation Linter, but when I run the template in cloudformation works fine
```yaml
  LtXXXXXX:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LtXXXXXX
      LaunchTemplateData:
        DisableApiTermination: true
        ImageId: !Ref LtXXXXXXAmi
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPair
      TagSpecifications:
        - ResourceType: instance
          Tags: 
            - Key: Name
              Value: XXXXXX
```

**Comment by kddejong** [comment]
What version of cfn-lint are you using and what error are you getting?

This template is not giving me any errors.  The formatting is a little lost in yours so not sure if I have it set correctly.
```yaml
LtXXXXXX:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LtXXXXXX
      LaunchTemplateData:
        DisableApiTermination: true
        ImageId: !Ref LtXXXXXXAmi
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPair
      TagSpecifications:
        - ResourceType: instance
          Tags:
            - Key: Name
              Value: XXXXXX
```
